apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  template:
    metadata:
      labels:
        app: auth-ms
        area: back
    spec:
      containers:
      - name: auth-ms
        image: jhonarias91/auth-ms:v10
        resources:
          limits:
            memory: "256Mi"
            cpu: "50m"
        ports:
        - containerPort: 3500
        envFrom:
        - configMapRef:
            name: auth-ms-config     
---

apiVersion: v1
kind: Service
metadata:
  name: auth-ms
spec:
  selector:
    app: auth-ms
  ports:
  - port: 3500
    targetPort: 3500
  type: LoadBalancer
  loadBalancerIP: 34.27.95.129