version: "3.9"
services:
  auth-ms:
    build: .
    ports:
      - 3500:3500
    env_file:
      - .env
    command: npm start     
    volumes:
      - .:/app 
    networks:
      - users-network

networks:
  users-network:
    external: true      