apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
        area: external
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog
        resources:
          limits:
            memory: "128Mi"
            cpu: "10m"
        ports:
        - containerPort: 1025
          hostPort: 1025
        - containerPort: 8025
          hostPort: 8025
---

apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
spec:
  selector:
    app: mailhog
  ports:
  - name: smtp
    protocol: TCP
    port: 1025
    targetPort: 1025
  - name: http
    protocol: TCP
    port: 8025
    targetPort: 8025
  type: ClusterIP