version: '3.9'
services:
  haproxy:
    build: .    
    ports:
      - "80:80"
    networks:
      - users-network
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  users-network:
    external: true