apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: usersdb-statefulset
  labels:
    app: usersdb
spec:
  serviceName: "usersdb-service"
  replicas: 1
  selector:
    matchLabels:
      app: usersdb
  template:
    metadata:
      labels:
        app: usersdb
        area: data
    spec:
      containers:
        - name: usersdb
          image: mysql:8
          env:
            - name: MYSQL_DATABASE
              value: users_db
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: TZ
              value: 'America/Bogota'
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: dbdata
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: "512Mi"
              cpu: "50m"
  volumeClaimTemplates:
    - metadata:
        name: dbdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 4Gi

---
apiVersion: v1
kind: Service
metadata:
  name: usersdb
spec:
  selector:
    app: usersdb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
