apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: productsdb-statefulset
  labels:
    app: productsdb
spec:
  serviceName: "productsdb"
  replicas: 1
  selector:
    matchLabels:
      app: productsdb
  template:
    metadata:
      labels:
        app: productsdb
        area: data
    spec:
      containers:
        - name: productsdb
          image: mysql:8
          env:
            - name: MYSQL_DATABASE
              value: products_db
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: TZ
              value: 'America/Bogota'
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: dbdata
              mountPath: /var/lib/mysql
          resources:          
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "100m"
  volumeClaimTemplates:
    - metadata:
        name: dbdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 4Gi

---
apiVersion: v1
kind: Service
metadata:
  name: productsdb
spec:
  selector:
    app: productsdb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
