apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-ms
  template:
    metadata:
      labels:
        app: users-ms
        area: back
    spec:
      containers:
      - name: users-ms
        image: jhonarias91/users-ms:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "10m"
        ports:
        - containerPort: 3500
---

apiVersion: v1
kind: Service
metadata:
  name: users-ms
spec:
  selector:
    app: users-ms
  ports:
  - port: 3500
    targetPort: 3500
  type: LoadBalancer 