apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-ms
  template:
    metadata:
      labels:
        app: users-ms
        area: back
    spec:
      containers:
      - name: users-ms
        image: jhonarias91/users-ms:v1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: users-ms-config
---

apiVersion: v1
kind: Service
metadata:
  name: users-ms
spec:
  selector:
    app: users-ms
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer 