apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-checkout-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-checkout
  template:
    metadata:
      labels:
        app: next-checkout
        area: front
    spec:
      containers:
      - name: next-checkout
        image: jhonarias91/next-checkout:v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: next-checkout
spec:
  selector:
    app: next-checkout
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP