apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        area: external
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
          #hostPort: 6379 gcp not allowed
---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP